### PR TITLE
Merge pull request #1 from googlesamples/master

### PR DESCRIPTION
**Pull request by arnaudaz**
A

### CODE REVIEW

**Comment by jguomoto** [comment]
Hi I don't see a change on this PR?

**Comment by andrewnakas** [comment]
Hey Jason sorry about the accidental pull, I totally was having lots of
trouble getting the files downloaded and accidentally pulled in
frustration. Fyi I have an interesting problem where I can't unzip the zip
package on my windows machine because the file paths and lengths are to
long.

Sorry about the confusion.

**Comment by jguomoto** [comment]
@andrewnakas could you try to clone the repo instead of unzip it?

**Comment by jguomoto** [comment]
I'm going to close the PR for now, but feel free to create a issue regarding the unzip problem.

**Pull request closed without merging**
